version: '3.7'

services:
  token-expressjs:
    container_name: token-expressjs
    build:
      context: .
      dockerfile: ./docker/Dockerfile.local
    restart: always
    ports:
      - "7319:80"
    volumes:
      - .:/usr/src/app
      - ./.env.local:/usr/src/app/.env:cached
      - ./docker/oauth/dev/oauth-public.key:/usr/src/app/storage/oauth-public.key:cached
      - ./docker/oauth/dev/oauth-public.key:/usr/src/app/storage/oauth-public.test.key:cached
      - /usr/src/app/node_modules
    environment:
      APP_ENV: local
      NODE_ENV: local
      HTTPS_METHOD: noredirect # support both http and https
    extra_hosts:
      - token-expressjs.local:127.0.0.1
    networks:
      network-horeca:
        aliases:
          - token-expressjs.local
networks:
  network-horeca:
    external: true